
import { GoogleGenAI, Modality, Part } from "@google/genai";
import { fileToGenerativePart } from '../utils/fileUtils';

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export const colorizeImage = async (imageFile: File, prompt: string): Promise<string> => {
    try {
        const imagePart = await fileToGenerativePart(imageFile);
        const textPart: Part = { text: prompt };

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [imagePart, textPart],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });
        
        for (const part of response.candidates?.[0]?.content?.parts || []) {
            if (part.inlineData) {
                const { data, mimeType } = part.inlineData;
                return `data:${mimeType};base64,${data}`;
            }
        }

        throw new Error("No image was generated by the AI.");

    } catch (error) {
        console.error("Error colorizing image:", error);
        if (error instanceof Error) {
            return Promise.reject(error.message);
        }
        return Promise.reject("An unknown error occurred during image colorization.");
    }
};
